# Generated by Django 2.2.16 on 2022-05-20 17:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0009_auto_20220514_1155"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="score",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="title",
            name="rating",
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
    ]
