# Generated by Django 2.2.16 on 2022-05-20 18:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0011_auto_20220520_2319"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="score",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        1, "Оценка не может быть меньше 1"
                    ),
                    django.core.validators.MaxValueValidator(
                        10, "Оценка не может быть выше 10"
                    ),
                ],
                verbose_name="Оценка",
            ),
        ),
    ]
